In [1]:
import tensorflow as tf

In [23]:
import numpy as np
import pandas as pd

In [2]:
x = tf.placeholder(tf.string)

In [4]:
with tf.Session() as sess:
    out = sess.run(x, feed_dict={x: 'hello'})

out

array('hello', dtype=object)

In [10]:
y = tf.placeholder(tf.string)
z = tf.placeholder(tf.float64)

In [12]:
with tf.Session() as sess:
    out = sess.run(x, feed_dict={x: 'sd', z: 23.1})

out

array('sd', dtype=object)

## Linear functions in TensorFlow

### Variable Value

In [13]:
x = tf.Variable(5)

In [15]:
with tf.Session() as sess:
    out = sess.run(x)
    print(out)

FailedPreconditionError: Attempting to use uninitialized value Variable
	 [[Node: _send_Variable_0 = _Send[T=DT_INT32, client_terminated=true, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=-2435528620273360348, tensor_name="Variable:0", _device="/job:localhost/replica:0/task:0/cpu:0"](Variable)]]

## run tf.global_variables_initializer()
before run variable

In [16]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    out = sess.run(x)
    print(out)

5


In [19]:
features = 120
labels = 5
weights = tf.Variable(tf.truncated_normal((features, labels)))

In [21]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    out = sess.run(weights)
    print(out)

[[ 4.55399990e-01 -2.82819271e-01 -5.55446029e-01 -1.41646966e-01
  -1.86546668e-01]
 [ 5.57281196e-01  4.67667937e-01  6.00399852e-01 -1.14741671e+00
  -4.05645579e-01]
 [ 1.31962526e+00  4.27463502e-02 -2.96465963e-01  1.22880116e-01
   6.19658589e-01]
 [-1.16359997e+00  2.79428989e-01 -4.31600094e-01 -5.98662496e-01
  -5.56701839e-01]
 [ 2.71432132e-01  1.30428338e+00  2.63353497e-01  8.18423867e-01
   3.38190436e-01]
 [ 6.11460030e-01  1.40603244e+00  4.96269733e-01 -4.57054734e-01
   3.90063792e-01]
 [ 2.99072802e-01 -5.15648842e-01 -1.52936208e+00  6.68457091e-01
  -1.67348778e+00]
 [-5.48426330e-01  2.36043409e-01 -1.59586155e+00  6.68756843e-01
   3.47890645e-01]
 [-1.11102152e+00  9.68882382e-01 -1.83477128e+00  2.89791375e-01
   1.42614973e+00]
 [ 1.28431225e+00  5.09505093e-01  9.65084553e-01 -1.83943915e+00
  -1.20591581e+00]
 [ 3.75360399e-01 -8.18412185e-01 -4.53563839e-01  3.36917102e-01
  -1.07867324e+00]
 [-6.04852140e-01 -1.26654983e+00 -1.21522260e+00 -5.04581816e-02

In [22]:
out.shape

(120, 5)

In [24]:
np.std(out)

0.90964603

In [25]:
np.mean(out)

-0.030137472

In [26]:
sess = tf.Session()

In [27]:
zeros = tf.zeros(3)

In [28]:
sess.run(zeros)

array([0., 0., 0.], dtype=float32)

In [29]:
zeros = tf.zeros((10,2))

In [30]:
sess.run(zeros)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)

In [33]:
sess.run(tf.log(10.0))

2.3025851

In [34]:
np.log(10)

2.302585092994046

In [35]:
np.log(100)

4.605170185988092

In [37]:
np.log(2.8342)

1.0417597104086331

In [38]:
softmax_data = [0.7, 0.2, 0.1]
one_hot_data = [1.0, 0.0, 0.0]

softmax = tf.placeholder(tf.float32)
one_hot = tf.placeholder(tf.float32)

# TODO: Print cross entropy from session


In [44]:
CE_softmax = tf.reduce_sum(-tf.log(tf.placeholder(softmax)))
CE_one_hot = tf.reduce_sum(-tf.log(tf.placeholder(one_hot)))

In [46]:
from tensorflow.examples.tutorials.mnist import input_data
import tensorflow as tf

n_input = 784  # MNIST data input (img shape: 28*28)
n_classes = 10  # MNIST total classes (0-9 digits)

# Import MNIST data
mnist = input_data.read_data_sets('/datasets/ud730/mnist', one_hot=True)

# The features are already scaled and the data is shuffled
train_features = mnist.train.images
test_features = mnist.test.images

train_labels = mnist.train.labels.astype(np.float32)
test_labels = mnist.test.labels.astype(np.float32)

# Weights & bias
weights = tf.Variable(tf.random_normal([n_input, n_classes]))
bias = tf.Variable(tf.random_normal([n_classes]))

PermissionDeniedError: /datasets

In [50]:
55000*784*32/8/256

673750.0

In [51]:
sess.run(tf.truncated_normal([2,3]))

array([[-1.57045   ,  0.82416546, -0.17996334],
       [ 1.7751507 ,  1.5353048 , -1.2379563 ]], dtype=float32)

In [52]:
50000/128

390.625

In [53]:
50000%128

80

In [54]:
range(0, 10, 4)

range(0, 10, 4)

In [55]:
list(range(0, 10, 4))

[0, 4, 8]

In [58]:
[1,34,21][0:10]

[1, 34, 21]

In [59]:
28*28

784

In [60]:
x,y = [12,3]

In [61]:
x

12

In [62]:
y

3